# Generated by Django 6.0.5 on 2026-05-22 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_payment_amount_alter_sale_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="assigned_salesman",
            field=models.ForeignKey(
                blank=True,
                help_text="Salesman this retailer is assigned to. Drives the Dukaan list filter.",
                limit_choices_to={"role": "salesman"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_retailers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="jio_partner_id",
            field=models.CharField(
                blank=True,
                help_text="Jio Partner PRM ID from the auto-refill report.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="face_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Jio-delivered credit (face value). amount × 1.03 = face_value.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="jio_order_id",
            field=models.CharField(
                blank=True,
                help_text="Jio Order ID — unique per refill. Lets the importer be idempotent.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
