# Generated by Django 6.0.5 on 2026-05-22 22:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_retailer_assigned_salesman_retailer_jio_partner_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="assigned_salesman",
            field=models.ForeignKey(
                blank=True,
                help_text="Salesman this retailer is assigned to. Drives the Dukaan list filter.",
                limit_choices_to=core.models._active_salesman_filter,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_retailers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
