# Generated by Django 6.0.5 on 2026-05-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_retailer_assigned_salesman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="core.visit",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="core.visit",
            ),
        ),
    ]
