# Generated by Django 6.0.5 on 2026-05-23 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_payment_visit_alter_sale_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram chat ID for payment-received notifications.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("received", "Payment received"),
                            ("updated", "Payment updated"),
                            ("cancelled", "Payment cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Telegram chat_id, +91XXXXXXXXXX phone, or WhatsApp address.",
                        max_length=64,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=128)),
                ("error", models.TextField(blank=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("send_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.payment",
                    ),
                ),
                (
                    "previous_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="core.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "send_after"],
                        name="core_notifi_status_30eabc_idx",
                    ),
                    models.Index(
                        fields=["payment", "kind"],
                        name="core_notifi_payment_3259af_idx",
                    ),
                ],
            },
        ),
    ]
