# Generated by Django 6.0.5 on 2026-05-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auditlog_reason_retailer_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("console", "Console (dev)"),
                    ("telegram", "Telegram"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=16,
            ),
        ),
    ]
