# Generated by Django 6.0.5 on 2026-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jio_fos_id",
            field=models.CharField(
                blank=True,
                help_text="Jio FOS ID from the auto-refill report. Matches rows during import.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
